const PROTOTYPE_RESOURCES = VERIFIED_SNAPSHOT_RESOURCES;
const PROTOTYPE_CHAPTERS = buildOutline(
  {topic:"云南少数民族音乐传承与当代发展"},
  PROTOTYPE_RESOURCES
);
const PROTOTYPE_ARTIFACTS = [];

Object.assign(window,{PROTOTYPE_RESOURCES,PROTOTYPE_CHAPTERS,PROTOTYPE_ARTIFACTS});
